name: MongoDB Backup

on:
  schedule:
    - cron: '0 2 * * *'  
  workflow_dispatch:

jobs:
  sync-mongo:
    runs-on: ubuntu-latest
    env:
      SOURCE_URI: ${{ secrets.SOURCE_URI }}
      TARGET_URI: ${{ secrets.TARGET_URI }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: cd backend && npm install

      - name: Run backup script
        run: cd backend && node mongoBackup.js
