name: MongoDB Backup

on:
  schedule:
    - cron: '0 2 * * *'  
  workflow_dispatch:     

jobs:
  backup-mongo:
    runs-on: ubuntu-latest

    steps:
      - name: Set up MongoDB tools
        run: |
          sudo apt-get update
          sudo apt-get install -y mongodb-clients

      - name: Dump source MongoDB
        run: |
          mongodump --uri="${{ secrets.MONGO_SOURCE_URI }}" --out=dump/

      - name: Restore to target MongoDB (overwrite)
        run: |
          mongorestore --uri="${{ secrets.MONGO_TARGET_URI }}" --drop dump/
