name: MongoDB Backup

on:
  schedule:
    - cron: '0 3 * * *'  
  workflow_dispatch:    

jobs:
  backup-mongo:
    runs-on: ubuntu-latest

    steps:
      - name: Set up MongoDB tools
        run: |
          sudo apt-get update
          sudo apt-get install -y mongodb-clients

      - name: Dump source MongoDB
        run: |
          mongodump --uri="${{ secrets.MONGO_SOURCE_URI }}" --out=dump/

      - name: Check if dump is not empty
        run: |
          if [ ! -d "dump" ] || [ -z "$(ls -A dump)" ]; then
            echo "Mongo dump failed or is empty. Skipping restore to prevent data loss."
            exit 1
          else
            echo "Dump successful. Proceeding with restore."
          fi

      - name: Restore to target MongoDB (overwrite)
        run: |
          mongorestore --uri="${{ secrets.MONGO_TARGET_URI }}" --drop dump/
