name: Price Alert & mailing

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    env:
      SOURCE_URI: ${{ secrets.SOURCE_URI }}
      TARGET_URI: ${{ secrets.TARGET_URI }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.15.0"

      - name: Install dependencies
        run: cd backend && npm install

      - name: Run priceAlert
        run: cd backend && node priceAlert.js
