name: Daily Scraper

on:
  schedule:
    - cron: "0 2 * * *" # vsak dan ob 3:00
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    env:
      DB_NAME: ${{ secrets.DB_NAME }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.15.0"

      - name: Install dependencies
        run: cd backend && npm install

      - name: Install Playwright browsers
        run: cd backend && npx playwright install --with-deps

      - name: Run all scrapers
        run: cd backend && npm run scrape
